# Travis-CI Build for ltr++ library

language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
script:
  - export CC=gcc-10
  - export CXX=g++-10
  - cmake

sudo: required

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake libgtest-dev valgrind lcov doxygen graphviz python-dev build-essential python3-pip
  - pip3 install sphinx breathe

install:
  - sudo apt-get install -y libboost-all-dev

before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test
  - make gcov 
  - make lcov 

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"