language: cpp

sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CC=gcc-10 CXX=g++-10"

branches:
  only:
    - master
    - dev

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake libgtest-dev valgrind lcov doxygen graphviz python-dev build-essential python3-pip
  - pip3 install sphinx breathe

install:
  - sudo apt-get install -y libboost-all-dev

before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test
  - make gcov 
  - make lcov 

  after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"