version: 1.0
language: cpp
dist: bionic

cache:
  - ccache
  - directories:
      - $TRAVIS_BUILD_DIR/vcpkg

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - build-essential
      - automake
      - gcc-10
      - g++-10
      - cppcheck
      - valgrind
      - doxygen
      - graphviz
      - lcov
  homebrew:
    packages:
      - automake
      - gcc
      - python3
      - ccache
    update: true

os:
  - linux

compiler:
  - g++-10

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake libgtest-dev valgrind lcov doxygen graphviz python-dev build-essential python3-pip
  - pip3 install sphinx breathe

install:
  - sudo apt-get install -y libboost-all-dev

before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test
  - make gcov 
  - make lcov 

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"