# Travis-CI Build for ranklib++ library

language: c++

sudo: required

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake check valgrind lcov libspdlog-dev libboost-all-dev

before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)